---

roles:
  - name: instrumentisto.coreos-bootstrap
    src: git+https://github.com/instrumentisto/ansible-coreos-bootstrap
    version: 4.0.1

# Check minimal Ansible version requirements before upgrading collections.
collections:
  # https://galaxy.ansible.com/ui/repo/published/community/digitalocean
  - name: community.digitalocean
    version: 1.27.0
  # https://galaxy.ansible.com/ui/repo/published/community/general
  - name: community.general
    version: 11.4.1
  # https://galaxy.ansible.com/ui/repo/published/containers/podman
  - name: containers.podman
    version: 1.18.0
  # https://galaxy.ansible.com/ui/repo/published/hetzner/hcloud
  - name: hetzner.hcloud
    version: 6.0.0
  # https://galaxy.ansible.com/ui/repo/published/kubernetes/core
  - name: kubernetes.core
    version: 6.2.0
  # https://galaxy.ansible.com/ui/repo/published/vultr/cloud
  - name: vultr.cloud
    version: 1.13.0
